// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: proto/neocoin.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Block struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *Header                `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Transactions  []*Transaction         `protobuf:"bytes,2,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Block) Reset() {
	*x = Block{}
	mi := &file_proto_neocoin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_proto_neocoin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_proto_neocoin_proto_rawDescGZIP(), []int{0}
}

func (x *Block) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *Block) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

type Header struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       int64                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	PrevBlock     string                 `protobuf:"bytes,2,opt,name=prev_block,json=prevBlock,proto3" json:"prev_block,omitempty"`
	MerkleRoot    string                 `protobuf:"bytes,3,opt,name=merkle_root,json=merkleRoot,proto3" json:"merkle_root,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Height        int64                  `protobuf:"varint,5,opt,name=height,proto3" json:"height,omitempty"`
	Difficulty    int64                  `protobuf:"varint,6,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	Nonce         string                 `protobuf:"bytes,7,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Miner         string                 `protobuf:"bytes,8,opt,name=miner,proto3" json:"miner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Header) Reset() {
	*x = Header{}
	mi := &file_proto_neocoin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_proto_neocoin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_proto_neocoin_proto_rawDescGZIP(), []int{1}
}

func (x *Header) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Header) GetPrevBlock() string {
	if x != nil {
		return x.PrevBlock
	}
	return ""
}

func (x *Header) GetMerkleRoot() string {
	if x != nil {
		return x.MerkleRoot
	}
	return ""
}

func (x *Header) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Header) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Header) GetDifficulty() int64 {
	if x != nil {
		return x.Difficulty
	}
	return 0
}

func (x *Header) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *Header) GetMiner() string {
	if x != nil {
		return x.Miner
	}
	return ""
}

type Transaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Txid          string                 `protobuf:"bytes,1,opt,name=txid,proto3" json:"txid,omitempty"`
	From          string                 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Amount        int64                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Fee           int64                  `protobuf:"varint,5,opt,name=fee,proto3" json:"fee,omitempty"`
	Nonce         int64                  `protobuf:"varint,6,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Signature     []byte                 `protobuf:"bytes,7,opt,name=signature,proto3" json:"signature,omitempty"`
	GasLimit      int64                  `protobuf:"varint,8,opt,name=gas_limit,json=gasLimit,proto3" json:"gas_limit,omitempty"`
	GasUsed       int64                  `protobuf:"varint,9,opt,name=gas_used,json=gasUsed,proto3" json:"gas_used,omitempty"`
	IsCoinbase    bool                   `protobuf:"varint,10,opt,name=is_coinbase,json=isCoinbase,proto3" json:"is_coinbase,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_proto_neocoin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_proto_neocoin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_proto_neocoin_proto_rawDescGZIP(), []int{2}
}

func (x *Transaction) GetTxid() string {
	if x != nil {
		return x.Txid
	}
	return ""
}

func (x *Transaction) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Transaction) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *Transaction) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Transaction) GetFee() int64 {
	if x != nil {
		return x.Fee
	}
	return 0
}

func (x *Transaction) GetNonce() int64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *Transaction) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *Transaction) GetGasLimit() int64 {
	if x != nil {
		return x.GasLimit
	}
	return 0
}

func (x *Transaction) GetGasUsed() int64 {
	if x != nil {
		return x.GasUsed
	}
	return 0
}

func (x *Transaction) GetIsCoinbase() bool {
	if x != nil {
		return x.IsCoinbase
	}
	return false
}

type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         int64                  `protobuf:"varint,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_proto_neocoin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_proto_neocoin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_proto_neocoin_proto_rawDescGZIP(), []int{3}
}

func (x *Ping) GetNonce() int64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *Ping) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type Pong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         int64                  `protobuf:"varint,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_proto_neocoin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_proto_neocoin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_proto_neocoin_proto_rawDescGZIP(), []int{4}
}

func (x *Pong) GetNonce() int64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

type GetHeaders struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LocatorHash   string                 `protobuf:"bytes,1,opt,name=locator_hash,json=locatorHash,proto3" json:"locator_hash,omitempty"`
	HashStop      string                 `protobuf:"bytes,2,opt,name=hash_stop,json=hashStop,proto3" json:"hash_stop,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHeaders) Reset() {
	*x = GetHeaders{}
	mi := &file_proto_neocoin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHeaders) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHeaders) ProtoMessage() {}

func (x *GetHeaders) ProtoReflect() protoreflect.Message {
	mi := &file_proto_neocoin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHeaders.ProtoReflect.Descriptor instead.
func (*GetHeaders) Descriptor() ([]byte, []int) {
	return file_proto_neocoin_proto_rawDescGZIP(), []int{5}
}

func (x *GetHeaders) GetLocatorHash() string {
	if x != nil {
		return x.LocatorHash
	}
	return ""
}

func (x *GetHeaders) GetHashStop() string {
	if x != nil {
		return x.HashStop
	}
	return ""
}

type Headers struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Headers       []*Header              `protobuf:"bytes,1,rep,name=headers,proto3" json:"headers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Headers) Reset() {
	*x = Headers{}
	mi := &file_proto_neocoin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Headers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Headers) ProtoMessage() {}

func (x *Headers) ProtoReflect() protoreflect.Message {
	mi := &file_proto_neocoin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Headers.ProtoReflect.Descriptor instead.
func (*Headers) Descriptor() ([]byte, []int) {
	return file_proto_neocoin_proto_rawDescGZIP(), []int{6}
}

func (x *Headers) GetHeaders() []*Header {
	if x != nil {
		return x.Headers
	}
	return nil
}

type GetBlocks struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LocatorHash   string                 `protobuf:"bytes,1,opt,name=locator_hash,json=locatorHash,proto3" json:"locator_hash,omitempty"`
	HashStop      string                 `protobuf:"bytes,2,opt,name=hash_stop,json=hashStop,proto3" json:"hash_stop,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlocks) Reset() {
	*x = GetBlocks{}
	mi := &file_proto_neocoin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlocks) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlocks) ProtoMessage() {}

func (x *GetBlocks) ProtoReflect() protoreflect.Message {
	mi := &file_proto_neocoin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlocks.ProtoReflect.Descriptor instead.
func (*GetBlocks) Descriptor() ([]byte, []int) {
	return file_proto_neocoin_proto_rawDescGZIP(), []int{7}
}

func (x *GetBlocks) GetLocatorHash() string {
	if x != nil {
		return x.LocatorHash
	}
	return ""
}

func (x *GetBlocks) GetHashStop() string {
	if x != nil {
		return x.HashStop
	}
	return ""
}

type GetTransactions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Txids         []string               `protobuf:"bytes,1,rep,name=txids,proto3" json:"txids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactions) Reset() {
	*x = GetTransactions{}
	mi := &file_proto_neocoin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactions) ProtoMessage() {}

func (x *GetTransactions) ProtoReflect() protoreflect.Message {
	mi := &file_proto_neocoin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactions.ProtoReflect.Descriptor instead.
func (*GetTransactions) Descriptor() ([]byte, []int) {
	return file_proto_neocoin_proto_rawDescGZIP(), []int{8}
}

func (x *GetTransactions) GetTxids() []string {
	if x != nil {
		return x.Txids
	}
	return nil
}

type Inv struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          int32                  `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Hashes        []string               `protobuf:"bytes,2,rep,name=hashes,proto3" json:"hashes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Inv) Reset() {
	*x = Inv{}
	mi := &file_proto_neocoin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Inv) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Inv) ProtoMessage() {}

func (x *Inv) ProtoReflect() protoreflect.Message {
	mi := &file_proto_neocoin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Inv.ProtoReflect.Descriptor instead.
func (*Inv) Descriptor() ([]byte, []int) {
	return file_proto_neocoin_proto_rawDescGZIP(), []int{9}
}

func (x *Inv) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Inv) GetHashes() []string {
	if x != nil {
		return x.Hashes
	}
	return nil
}

type GetData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Inv                 `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetData) Reset() {
	*x = GetData{}
	mi := &file_proto_neocoin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetData) ProtoMessage() {}

func (x *GetData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_neocoin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetData.ProtoReflect.Descriptor instead.
func (*GetData) Descriptor() ([]byte, []int) {
	return file_proto_neocoin_proto_rawDescGZIP(), []int{10}
}

func (x *GetData) GetItems() []*Inv {
	if x != nil {
		return x.Items
	}
	return nil
}

type NotFound struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hashes        []string               `protobuf:"bytes,1,rep,name=hashes,proto3" json:"hashes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotFound) Reset() {
	*x = NotFound{}
	mi := &file_proto_neocoin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotFound) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotFound) ProtoMessage() {}

func (x *NotFound) ProtoReflect() protoreflect.Message {
	mi := &file_proto_neocoin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotFound.ProtoReflect.Descriptor instead.
func (*NotFound) Descriptor() ([]byte, []int) {
	return file_proto_neocoin_proto_rawDescGZIP(), []int{11}
}

func (x *NotFound) GetHashes() []string {
	if x != nil {
		return x.Hashes
	}
	return nil
}

type Version struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       int64                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Services      int64                  `protobuf:"varint,2,opt,name=services,proto3" json:"services,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	AddrRecv      int64                  `protobuf:"varint,4,opt,name=addr_recv,json=addrRecv,proto3" json:"addr_recv,omitempty"`
	AddrFrom      int64                  `protobuf:"varint,5,opt,name=addr_from,json=addrFrom,proto3" json:"addr_from,omitempty"`
	Nonce         int64                  `protobuf:"varint,6,opt,name=nonce,proto3" json:"nonce,omitempty"`
	UserAgent     string                 `protobuf:"bytes,7,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	StartHeight   int64                  `protobuf:"varint,8,opt,name=start_height,json=startHeight,proto3" json:"start_height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Version) Reset() {
	*x = Version{}
	mi := &file_proto_neocoin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Version) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Version) ProtoMessage() {}

func (x *Version) ProtoReflect() protoreflect.Message {
	mi := &file_proto_neocoin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Version.ProtoReflect.Descriptor instead.
func (*Version) Descriptor() ([]byte, []int) {
	return file_proto_neocoin_proto_rawDescGZIP(), []int{12}
}

func (x *Version) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Version) GetServices() int64 {
	if x != nil {
		return x.Services
	}
	return 0
}

func (x *Version) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Version) GetAddrRecv() int64 {
	if x != nil {
		return x.AddrRecv
	}
	return 0
}

func (x *Version) GetAddrFrom() int64 {
	if x != nil {
		return x.AddrFrom
	}
	return 0
}

func (x *Version) GetNonce() int64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *Version) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *Version) GetStartHeight() int64 {
	if x != nil {
		return x.StartHeight
	}
	return 0
}

type Verack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Verack) Reset() {
	*x = Verack{}
	mi := &file_proto_neocoin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Verack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Verack) ProtoMessage() {}

func (x *Verack) ProtoReflect() protoreflect.Message {
	mi := &file_proto_neocoin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Verack.ProtoReflect.Descriptor instead.
func (*Verack) Descriptor() ([]byte, []int) {
	return file_proto_neocoin_proto_rawDescGZIP(), []int{13}
}

type Reject struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Ccode         string                 `protobuf:"bytes,2,opt,name=ccode,proto3" json:"ccode,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reject) Reset() {
	*x = Reject{}
	mi := &file_proto_neocoin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reject) ProtoMessage() {}

func (x *Reject) ProtoReflect() protoreflect.Message {
	mi := &file_proto_neocoin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reject.ProtoReflect.Descriptor instead.
func (*Reject) Descriptor() ([]byte, []int) {
	return file_proto_neocoin_proto_rawDescGZIP(), []int{14}
}

func (x *Reject) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Reject) GetCcode() string {
	if x != nil {
		return x.Ccode
	}
	return ""
}

func (x *Reject) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type P2PMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *P2PMessage) Reset() {
	*x = P2PMessage{}
	mi := &file_proto_neocoin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *P2PMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*P2PMessage) ProtoMessage() {}

func (x *P2PMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_neocoin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use P2PMessage.ProtoReflect.Descriptor instead.
func (*P2PMessage) Descriptor() ([]byte, []int) {
	return file_proto_neocoin_proto_rawDescGZIP(), []int{15}
}

func (x *P2PMessage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *P2PMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *P2PMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type Hello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Protocol      uint32                 `protobuf:"varint,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	ChainId       uint64                 `protobuf:"varint,2,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	RulesHash     string                 `protobuf:"bytes,3,opt,name=rules_hash,json=rulesHash,proto3" json:"rules_hash,omitempty"`
	NodeId        string                 `protobuf:"bytes,4,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	TimeUnix      int64                  `protobuf:"varint,5,opt,name=time_unix,json=timeUnix,proto3" json:"time_unix,omitempty"`
	Port          uint32                 `protobuf:"varint,6,opt,name=port,proto3" json:"port,omitempty"`
	Services      uint64                 `protobuf:"varint,7,opt,name=services,proto3" json:"services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_proto_neocoin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_proto_neocoin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_proto_neocoin_proto_rawDescGZIP(), []int{16}
}

func (x *Hello) GetProtocol() uint32 {
	if x != nil {
		return x.Protocol
	}
	return 0
}

func (x *Hello) GetChainId() uint64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *Hello) GetRulesHash() string {
	if x != nil {
		return x.RulesHash
	}
	return ""
}

func (x *Hello) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Hello) GetTimeUnix() int64 {
	if x != nil {
		return x.TimeUnix
	}
	return 0
}

func (x *Hello) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Hello) GetServices() uint64 {
	if x != nil {
		return x.Services
	}
	return 0
}

type PeerAddress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port          uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerAddress) Reset() {
	*x = PeerAddress{}
	mi := &file_proto_neocoin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerAddress) ProtoMessage() {}

func (x *PeerAddress) ProtoReflect() protoreflect.Message {
	mi := &file_proto_neocoin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerAddress.ProtoReflect.Descriptor instead.
func (*PeerAddress) Descriptor() ([]byte, []int) {
	return file_proto_neocoin_proto_rawDescGZIP(), []int{17}
}

func (x *PeerAddress) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *PeerAddress) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *PeerAddress) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type Addr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addresses     []*PeerAddress         `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Addr) Reset() {
	*x = Addr{}
	mi := &file_proto_neocoin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Addr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Addr) ProtoMessage() {}

func (x *Addr) ProtoReflect() protoreflect.Message {
	mi := &file_proto_neocoin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Addr.ProtoReflect.Descriptor instead.
func (*Addr) Descriptor() ([]byte, []int) {
	return file_proto_neocoin_proto_rawDescGZIP(), []int{18}
}

func (x *Addr) GetAddresses() []*PeerAddress {
	if x != nil {
		return x.Addresses
	}
	return nil
}

type GetAddr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAddr) Reset() {
	*x = GetAddr{}
	mi := &file_proto_neocoin_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAddr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAddr) ProtoMessage() {}

func (x *GetAddr) ProtoReflect() protoreflect.Message {
	mi := &file_proto_neocoin_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAddr.ProtoReflect.Descriptor instead.
func (*GetAddr) Descriptor() ([]byte, []int) {
	return file_proto_neocoin_proto_rawDescGZIP(), []int{19}
}

var File_proto_neocoin_proto protoreflect.FileDescriptor

const file_proto_neocoin_proto_rawDesc = "" +
	"\n" +
	"\x13proto/neocoin.proto\x12\aneocoin\"j\n" +
	"\x05Block\x12'\n" +
	"\x06header\x18\x01 \x01(\v2\x0f.neocoin.HeaderR\x06header\x128\n" +
	"\ftransactions\x18\x02 \x03(\v2\x14.neocoin.TransactionR\ftransactions\"\xe4\x01\n" +
	"\x06Header\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x03R\aversion\x12\x1d\n" +
	"\n" +
	"prev_block\x18\x02 \x01(\tR\tprevBlock\x12\x1f\n" +
	"\vmerkle_root\x18\x03 \x01(\tR\n" +
	"merkleRoot\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12\x16\n" +
	"\x06height\x18\x05 \x01(\x03R\x06height\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x06 \x01(\x03R\n" +
	"difficulty\x12\x14\n" +
	"\x05nonce\x18\a \x01(\tR\x05nonce\x12\x14\n" +
	"\x05miner\x18\b \x01(\tR\x05miner\"\xfc\x01\n" +
	"\vTransaction\x12\x12\n" +
	"\x04txid\x18\x01 \x01(\tR\x04txid\x12\x12\n" +
	"\x04from\x18\x02 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x03 \x01(\tR\x02to\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x03R\x06amount\x12\x10\n" +
	"\x03fee\x18\x05 \x01(\x03R\x03fee\x12\x14\n" +
	"\x05nonce\x18\x06 \x01(\x03R\x05nonce\x12\x1c\n" +
	"\tsignature\x18\a \x01(\fR\tsignature\x12\x1b\n" +
	"\tgas_limit\x18\b \x01(\x03R\bgasLimit\x12\x19\n" +
	"\bgas_used\x18\t \x01(\x03R\agasUsed\x12\x1f\n" +
	"\vis_coinbase\x18\n" +
	" \x01(\bR\n" +
	"isCoinbase\":\n" +
	"\x04Ping\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\x03R\x05nonce\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"\x1c\n" +
	"\x04Pong\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\x03R\x05nonce\"L\n" +
	"\n" +
	"GetHeaders\x12!\n" +
	"\flocator_hash\x18\x01 \x01(\tR\vlocatorHash\x12\x1b\n" +
	"\thash_stop\x18\x02 \x01(\tR\bhashStop\"4\n" +
	"\aHeaders\x12)\n" +
	"\aheaders\x18\x01 \x03(\v2\x0f.neocoin.HeaderR\aheaders\"K\n" +
	"\tGetBlocks\x12!\n" +
	"\flocator_hash\x18\x01 \x01(\tR\vlocatorHash\x12\x1b\n" +
	"\thash_stop\x18\x02 \x01(\tR\bhashStop\"'\n" +
	"\x0fGetTransactions\x12\x14\n" +
	"\x05txids\x18\x01 \x03(\tR\x05txids\"1\n" +
	"\x03Inv\x12\x12\n" +
	"\x04type\x18\x01 \x01(\x05R\x04type\x12\x16\n" +
	"\x06hashes\x18\x02 \x03(\tR\x06hashes\"-\n" +
	"\aGetData\x12\"\n" +
	"\x05items\x18\x01 \x03(\v2\f.neocoin.InvR\x05items\"\"\n" +
	"\bNotFound\x12\x16\n" +
	"\x06hashes\x18\x01 \x03(\tR\x06hashes\"\xef\x01\n" +
	"\aVersion\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x03R\aversion\x12\x1a\n" +
	"\bservices\x18\x02 \x01(\x03R\bservices\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x1b\n" +
	"\taddr_recv\x18\x04 \x01(\x03R\baddrRecv\x12\x1b\n" +
	"\taddr_from\x18\x05 \x01(\x03R\baddrFrom\x12\x14\n" +
	"\x05nonce\x18\x06 \x01(\x03R\x05nonce\x12\x1d\n" +
	"\n" +
	"user_agent\x18\a \x01(\tR\tuserAgent\x12!\n" +
	"\fstart_height\x18\b \x01(\x03R\vstartHeight\"\b\n" +
	"\x06Verack\"P\n" +
	"\x06Reject\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x14\n" +
	"\x05ccode\x18\x02 \x01(\tR\x05ccode\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"X\n" +
	"\n" +
	"P2PMessage\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"\xc3\x01\n" +
	"\x05Hello\x12\x1a\n" +
	"\bprotocol\x18\x01 \x01(\rR\bprotocol\x12\x19\n" +
	"\bchain_id\x18\x02 \x01(\x04R\achainId\x12\x1d\n" +
	"\n" +
	"rules_hash\x18\x03 \x01(\tR\trulesHash\x12\x17\n" +
	"\anode_id\x18\x04 \x01(\tR\x06nodeId\x12\x1b\n" +
	"\ttime_unix\x18\x05 \x01(\x03R\btimeUnix\x12\x12\n" +
	"\x04port\x18\x06 \x01(\rR\x04port\x12\x1a\n" +
	"\bservices\x18\a \x01(\x04R\bservices\"O\n" +
	"\vPeerAddress\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\":\n" +
	"\x04Addr\x122\n" +
	"\taddresses\x18\x01 \x03(\v2\x14.neocoin.PeerAddressR\taddresses\"\t\n" +
	"\aGetAddrB\"Z github.com/nogochain/nogo/protob\x06proto3"

var (
	file_proto_neocoin_proto_rawDescOnce sync.Once
	file_proto_neocoin_proto_rawDescData []byte
)

func file_proto_neocoin_proto_rawDescGZIP() []byte {
	file_proto_neocoin_proto_rawDescOnce.Do(func() {
		file_proto_neocoin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_neocoin_proto_rawDesc), len(file_proto_neocoin_proto_rawDesc)))
	})
	return file_proto_neocoin_proto_rawDescData
}

var file_proto_neocoin_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_proto_neocoin_proto_goTypes = []any{
	(*Block)(nil),           // 0: neocoin.Block
	(*Header)(nil),          // 1: neocoin.Header
	(*Transaction)(nil),     // 2: neocoin.Transaction
	(*Ping)(nil),            // 3: neocoin.Ping
	(*Pong)(nil),            // 4: neocoin.Pong
	(*GetHeaders)(nil),      // 5: neocoin.GetHeaders
	(*Headers)(nil),         // 6: neocoin.Headers
	(*GetBlocks)(nil),       // 7: neocoin.GetBlocks
	(*GetTransactions)(nil), // 8: neocoin.GetTransactions
	(*Inv)(nil),             // 9: neocoin.Inv
	(*GetData)(nil),         // 10: neocoin.GetData
	(*NotFound)(nil),        // 11: neocoin.NotFound
	(*Version)(nil),         // 12: neocoin.Version
	(*Verack)(nil),          // 13: neocoin.Verack
	(*Reject)(nil),          // 14: neocoin.Reject
	(*P2PMessage)(nil),      // 15: neocoin.P2PMessage
	(*Hello)(nil),           // 16: neocoin.Hello
	(*PeerAddress)(nil),     // 17: neocoin.PeerAddress
	(*Addr)(nil),            // 18: neocoin.Addr
	(*GetAddr)(nil),         // 19: neocoin.GetAddr
}
var file_proto_neocoin_proto_depIdxs = []int32{
	1,  // 0: neocoin.Block.header:type_name -> neocoin.Header
	2,  // 1: neocoin.Block.transactions:type_name -> neocoin.Transaction
	1,  // 2: neocoin.Headers.headers:type_name -> neocoin.Header
	9,  // 3: neocoin.GetData.items:type_name -> neocoin.Inv
	17, // 4: neocoin.Addr.addresses:type_name -> neocoin.PeerAddress
	5,  // [5:5] is the sub-list for method output_type
	5,  // [5:5] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_neocoin_proto_init() }
func file_proto_neocoin_proto_init() {
	if File_proto_neocoin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_neocoin_proto_rawDesc), len(file_proto_neocoin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_neocoin_proto_goTypes,
		DependencyIndexes: file_proto_neocoin_proto_depIdxs,
		MessageInfos:      file_proto_neocoin_proto_msgTypes,
	}.Build()
	File_proto_neocoin_proto = out.File
	file_proto_neocoin_proto_goTypes = nil
	file_proto_neocoin_proto_depIdxs = nil
}
