#!/usr/bin/env bash
set -euo pipefail

if ! command -v docker >/dev/null 2>&1; then
  echo "docker not found"
  exit 1
fi
if ! docker compose version >/dev/null 2>&1; then
  echo "docker compose not found"
  exit 1
fi

ROOT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

ENV_FILE="${1:-.env.mainnet}"
GENESIS_PATH="${GENESIS_PATH:-genesis/mainnet.json}"

wallet_addr() {
  ./blockchain/blockchain create_wallet \
    | python -c 'import json,sys; print(json.loads(sys.stdin.read())["address"])'
}

rand_hex() {
  python -c 'import secrets; print(secrets.token_hex(32))'
}

echo "Generating genesis allocation address..."
GENESIS_ADDR="$(wallet_addr)"

echo "Generating miner address..."
MINER_ADDR="$(wallet_addr)"

echo "Generating admin token..."
ADMIN_TOKEN="$(rand_hex)"

# Convention: mainnet is CHAIN_ID=1; override by exporting CHAIN_ID before running.
CHAIN_ID="${CHAIN_ID:-1}"
GENESIS_SUPPLY="${GENESIS_SUPPLY:-2100000000000000}"
GENESIS_TIMESTAMP_UNIX="${GENESIS_TIMESTAMP_UNIX:-1740441600}"
GENESIS_MESSAGE="${GENESIS_MESSAGE:-NogoChain launches - Educational PoW chain with AI auditor - February 2025}"
INITIAL_BLOCK_REWARD="${INITIAL_BLOCK_REWARD:-5000000000}"
HALVING_INTERVAL="${HALVING_INTERVAL:-210000}"
MINER_FEE_SHARE="${MINER_FEE_SHARE:-100}"
TAIL_EMISSION="${TAIL_EMISSION:-0}"

DIFFICULTY_ENABLE="${DIFFICULTY_ENABLE:-true}"
DIFFICULTY_TARGET_MS="${DIFFICULTY_TARGET_MS:-60000}"
DIFFICULTY_WINDOW="${DIFFICULTY_WINDOW:-100}"
DIFFICULTY_MAX_STEP_BITS="${DIFFICULTY_MAX_STEP_BITS:-1}"
DIFFICULTY_MIN_BITS="${DIFFICULTY_MIN_BITS:-1}"
DIFFICULTY_MAX_BITS="${DIFFICULTY_MAX_BITS:-255}"
GENESIS_DIFFICULTY_BITS="${GENESIS_DIFFICULTY_BITS:-18}"
MTP_WINDOW="${MTP_WINDOW:-11}"
MAX_TIME_DRIFT="${MAX_TIME_DRIFT:-7200}"
MAX_BLOCK_SIZE="${MAX_BLOCK_SIZE:-1000000}"
MERKLE_ENABLE="${MERKLE_ENABLE:-true}"
MERKLE_ACTIVATION_HEIGHT="${MERKLE_ACTIVATION_HEIGHT:-0}"
BINARY_ENCODING_ENABLE="${BINARY_ENCODING_ENABLE:-true}"
BINARY_ENCODING_ACTIVATION_HEIGHT="${BINARY_ENCODING_ACTIVATION_HEIGHT:-0}"

bool_json() {
  case "${1,,}" in
    1|true|yes|y) echo "true" ;;
    *) echo "false" ;;
  esac
}

mkdir -p "$(dirname "$GENESIS_PATH")"
cat >"$GENESIS_PATH" <<EOF
{
  "network": "nogochain-mainnet",
  "chainId": $CHAIN_ID,
  "timestamp": $GENESIS_TIMESTAMP_UNIX,
  "genesisMinerAddress": "$GENESIS_ADDR",
  "initialSupply": "$GENESIS_SUPPLY",
  "genesisMessage": "$GENESIS_MESSAGE",
  "monetaryPolicy": {
    "initialBlockReward": "$INITIAL_BLOCK_REWARD",
    "halvingInterval": $HALVING_INTERVAL,
    "minerFeeShare": $MINER_FEE_SHARE,
    "tailEmission": "$TAIL_EMISSION"
  },
  "consensusParams": {
    "difficultyEnable": $(bool_json "$DIFFICULTY_ENABLE"),
    "difficultyTargetMs": $DIFFICULTY_TARGET_MS,
    "difficultyWindow": $DIFFICULTY_WINDOW,
    "difficultyMaxStepBits": $DIFFICULTY_MAX_STEP_BITS,
    "difficultyMinBits": $DIFFICULTY_MIN_BITS,
    "difficultyMaxBits": $DIFFICULTY_MAX_BITS,
    "genesisDifficultyBits": $GENESIS_DIFFICULTY_BITS,
    "medianTimePastWindow": $MTP_WINDOW,
    "maxTimeDrift": $MAX_TIME_DRIFT,
    "maxBlockSize": $MAX_BLOCK_SIZE,
    "merkleEnable": $(bool_json "$MERKLE_ENABLE"),
    "merkleActivationHeight": $MERKLE_ACTIVATION_HEIGHT,
    "binaryEncodingEnable": $(bool_json "$BINARY_ENCODING_ENABLE"),
    "binaryEncodingActivationHeight": $BINARY_ENCODING_ACTIVATION_HEIGHT
  }
}
EOF

cat >"$ENV_FILE" <<EOF
# Generated by scripts/mainnet_bootstrap.sh
# NOTE: This creates a fresh single-node network. If you want to "reset",
# delete ./blockchain/data (or run docker compose down -v if using named volumes).
CHAIN_ID=$CHAIN_ID
GENESIS_PATH=$GENESIS_PATH

MINER_ADDRESS=$MINER_ADDR

# Required to enable admin endpoints (mine/audit/add-block). Keep this secret.
ADMIN_TOKEN=$ADMIN_TOKEN
EOF

echo "Wrote $ENV_FILE"
echo "Wrote $GENESIS_PATH"
echo
echo "Start the node:"
echo "  docker compose --env-file $ENV_FILE -f docker-compose.yml -f docker-compose.mainnet.yml up -d --build"
