#!/usr/bin/env bash
set -euo pipefail

if ! command -v docker >/dev/null 2>&1; then
  echo "docker not found"
  exit 1
fi
if ! docker compose version >/dev/null 2>&1; then
  echo "docker compose not found"
  exit 1
fi

ROOT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

ENV_FILE="${1:-.env.mainnet}"
GENESIS_PATH="${GENESIS_PATH:-genesis/mainnet.json}"

wallet_addr() {
  ./blockchain/blockchain create_wallet \
    | python -c 'import json,sys; print(json.loads(sys.stdin.read())["address"])'
}

rand_hex() {
  python -c 'import secrets; print(secrets.token_hex(32))'
}

echo "Generating genesis allocation address..."
GENESIS_ADDR="$(wallet_addr)"

echo "Generating miner address..."
MINER_ADDR="$(wallet_addr)"

echo "Generating admin token..."
ADMIN_TOKEN="$(rand_hex)"

# Convention: mainnet is CHAIN_ID=1; override by exporting CHAIN_ID before running.
CHAIN_ID="${CHAIN_ID:-1}"
GENESIS_SUPPLY="${GENESIS_SUPPLY:-2100000000000000}"
GENESIS_TIMESTAMP_UNIX="${GENESIS_TIMESTAMP_UNIX:-1780315200}"
GENESIS_MESSAGE="${GENESIS_MESSAGE:-NogoChain Mainnet Launch - A new era of decentralized finance - 2026-06-01 12:00:00 UTC}"
INITIAL_BLOCK_REWARD="${INITIAL_BLOCK_REWARD:-800000000}"        # 8 NOGO in wei (1 NOGO = 10^8 wei)
ANNUAL_REDUCTION_PERCENT="${ANNUAL_REDUCTION_PERCENT:-10}"       # 10% annual reduction
MINIMUM_BLOCK_REWARD="${MINIMUM_BLOCK_REWARD:-10000000}"        # 0.1 NOGO minimum reward
MINER_REWARD_SHARE="${MINER_REWARD_SHARE:-99}"                  # 99% of block reward to miner
GENESIS_SHARE="${GENESIS_SHARE:-1}"                             # 1% of block reward to genesis address
MINER_FEE_SHARE="${MINER_FEE_SHARE:-0}"                         # 0% - all fees are burned
TAIL_EMISSION="${TAIL_EMISSION:-0}"

DIFFICULTY_ENABLE="${DIFFICULTY_ENABLE:-true}"
DIFFICULTY_TARGET_MS="${DIFFICULTY_TARGET_MS:-30000}"       # 30 second block time
DIFFICULTY_WINDOW="${DIFFICULTY_WINDOW:-10}"                # PI controller window
DIFFICULTY_MAX_STEP="${DIFFICULTY_MAX_STEP:-4}"             # Max difficulty change per block (4x)
DIFFICULTY_MIN_BITS="${DIFFICULTY_MIN_BITS:-1}"
DIFFICULTY_MAX_BITS="${DIFFICULTY_MAX_BITS:-255}"
GENESIS_DIFFICULTY_BITS="${GENESIS_DIFFICULTY_BITS:-100}"    # CPU-minable genesis
MTP_WINDOW="${MTP_WINDOW:-11}"
MAX_TIME_DRIFT="${MAX_TIME_DRIFT:-7200}"
MAX_BLOCK_SIZE="${MAX_BLOCK_SIZE:-4000000}"                  # 4MB max block size
MERKLE_ENABLE="${MERKLE_ENABLE:-true}"
MERKLE_ACTIVATION_HEIGHT="${MERKLE_ACTIVATION_HEIGHT:-0}"
BINARY_ENCODING_ENABLE="${BINARY_ENCODING_ENABLE:-true}"
BINARY_ENCODING_ACTIVATION_HEIGHT="${BINARY_ENCODING_ACTIVATION_HEIGHT:-0}"

bool_json() {
  case "${1,,}" in
    1|true|yes|y) echo "true" ;;
    *) echo "false" ;;
  esac
}

mkdir -p "$(dirname "$GENESIS_PATH")"
cat >"$GENESIS_PATH" <<EOF
{
  "network": "nogochain-mainnet",
  "chainId": $CHAIN_ID,
  "timestamp": $GENESIS_TIMESTAMP_UNIX,
  "genesisMinerAddress": "$GENESIS_ADDR",
  "initialSupply": "$GENESIS_SUPPLY",
  "genesisMessage": "$GENESIS_MESSAGE",
  "monetaryPolicy": {
    "initialBlockReward": "$INITIAL_BLOCK_REWARD",
    "minimumBlockReward": "$MINIMUM_BLOCK_REWARD",
    "annualReductionPercent": $ANNUAL_REDUCTION_PERCENT,
    "minerRewardShare": $MINER_REWARD_SHARE,
    "genesisShare": $GENESIS_SHARE,
    "minerFeeShare": $MINER_FEE_SHARE,
    "communityFundShare": 0,
    "integrityPoolShare": 0,
    "tailEmission": "$TAIL_EMISSION"
  },
  "consensusParams": {
    "difficultyEnable": $(bool_json "$DIFFICULTY_ENABLE"),
    "targetBlockTime": $DIFFICULTY_TARGET_MS,
    "difficultyWindow": $DIFFICULTY_WINDOW,
    "difficultyMaxStep": $DIFFICULTY_MAX_STEP,
    "minDifficultyBits": $DIFFICULTY_MIN_BITS,
    "maxDifficultyBits": $DIFFICULTY_MAX_BITS,
    "genesisDifficultyBits": $GENESIS_DIFFICULTY_BITS,
    "medianTimePastWindow": $MTP_WINDOW,
    "maxTimeDrift": $MAX_TIME_DRIFT,
    "maxBlockSize": $MAX_BLOCK_SIZE,
    "merkleEnable": $(bool_json "$MERKLE_ENABLE"),
    "merkleActivationHeight": $MERKLE_ACTIVATION_HEIGHT,
    "binaryEncodingEnable": $(bool_json "$BINARY_ENCODING_ENABLE"),
    "binaryEncodingActivationHeight": $BINARY_ENCODING_ACTIVATION_HEIGHT
  }
}
EOF

cat >"$ENV_FILE" <<EOF
# Generated by scripts/mainnet_bootstrap.sh
# NOTE: This creates a fresh single-node network. If you want to "reset",
# delete ./blockchain/data (or run docker compose down -v if using named volumes).
CHAIN_ID=$CHAIN_ID
GENESIS_PATH=$GENESIS_PATH

MINER_ADDRESS=$MINER_ADDR

# Required to enable admin endpoints (mine/audit/add-block). Keep this secret.
ADMIN_TOKEN=$ADMIN_TOKEN
EOF

echo "Wrote $ENV_FILE"
echo "Wrote $GENESIS_PATH"
echo
echo "Start the node:"
echo "  docker compose --env-file $ENV_FILE -f docker-compose.yml -f docker-compose.mainnet.yml up -d --build"
